/* sqlite_baremetal_config.h -- hand-written build config for SQLite
 * 3.46.1 on this port (see scripts/get-sqlite.sh). SQLite is vendored
 * unmodified as its own amalgamation (sqlite3.c/sqlite3.h); this is
 * the header its SQLITE_CUSTOM_INCLUDE hook pulls in (near the very
 * top of sqlite3.c, ahead of everything else in the file, including
 * its own OS-detection block) instead of a config generated by
 * `./configure` or a platform #ifdef sqlite3.c would otherwise fall
 * back to.
 *
 * SQLITE_OS_OTHER=1 below is the load-bearing choice this whole file
 * hangs off of: it tells sqlite3.c to skip compiling its own os_unix.c
 * section (~15k lines: POSIX advisory locking via fcntl(), mmap()-
 * backed WAL-index shared memory, /dev/urandom, getcwd(), ...) and
 * instead expect the application to supply a VFS of its own, plus
 * sqlite3_os_init()/sqlite3_os_end(). port/sqlite_port/sqlite_vfs.c
 * is that VFS -- a small, direct implementation over this port's own
 * open/read/write/lseek/close/unlink/ftruncate (posix_shim.c/bmfs.c),
 * along the same lines as tls_shim.c/net_shim.c/dns_shim.c being
 * hand-written instead of dragging in a general-purpose POSIX
 * implementation this environment can't fully back. See that file's
 * header for what each VFS method does and why.
 */

#ifndef SQLITE_PORT_SQLITE_BAREMETAL_CONFIG_H
#define SQLITE_PORT_SQLITE_BAREMETAL_CONFIG_H

/* No os_unix.c/os_win.c -- port/sqlite_port/sqlite_vfs.c provides the
 * VFS and sqlite3_os_init()/sqlite3_os_end() instead (see this file's
 * header). */
#define SQLITE_OS_OTHER 1

/* Single-threaded only, matches this port throughout (see
 * OPENISSUES.md's "Process model" section) -- pthread_create() isn't
 * wired up. This compiles SQLite's mutex layer down to true no-ops
 * rather than ones that merely never contend. */
#define SQLITE_THREADSAFE 0

/* No dlopen()-equivalent on this port (no dynamic linking at all --
 * see OPENISSUES.md's "General" section) for sqlite3_load_extension()
 * to use. */
#define SQLITE_OMIT_LOAD_EXTENSION 1

/* WAL mode's -wal/-shm files need xShmMap()/xShmLock()/xShmBarrier()/
 * xShmUnmap() (mmap()-backed shared memory, negotiated between
 * connections) -- meaningless with exactly one process, ever, on this
 * port, and sqlite_vfs.c's sqlite3_io_methods deliberately stops at
 * iVersion 1 (no xShm-prefixed or xFetch/xUnfetch slots at all) to
 * match. The default rollback-journal mode (what every app gets
 * unless it opts into PRAGMA journal_mode=WAL) doesn't use any of
 * this.
 */
#define SQLITE_OMIT_WAL 1

/* No mmap() worth having here: posix_shim.c's mmap() is a bump
 * allocator over the same fixed heap arena brk() draws from, with
 * munmap() a documented no-op (OPENISSUES.md's "Heap" section) --
 * every byte an mmap'd file view would hold is heap this port can't
 * get back. Forced to 0 (not just defaulted) so PRAGMA mmap_size can't
 * re-enable it at runtime either. */
#define SQLITE_MAX_MMAP_SIZE 0
#define SQLITE_DEFAULT_MMAP_SIZE 0

/* No timezone database on this port to make SQLite's 'localtime'/
 * 'utc' datetime() modifiers meaningful -- b_system(WALLCLOCK) (see
 * posix_shim.c's clock_gettime()) is UTC-only with no sub-second
 * component either. Datetime functions still work in every other
 * respect (they're pure calendar arithmetic); this just drops the
 * two modifiers that would otherwise silently assume UTC==local. */
#define SQLITE_OMIT_LOCALTIME 1

/* Always spill TEMP tables/indices (and the transient sorters/
 * statement journals ORDER BY, GROUP BY, CREATE INDEX, etc. use under
 * the hood) to memory rather than a temp file, regardless of what
 * PRAGMA temp_store requests. This is what keeps sqlite_vfs.c's
 * xOpen() from needing a real temp-file-name generator/directory for
 * the common case -- see its header comment for the (rare, still
 * handled) remaining exception: multi-database (ATTACH) commits'
 * master journal. */
#define SQLITE_TEMP_STORE 3

/* Drops the pre-3.x compatibility shims (sqlite3_trace(),
 * sqlite3_profile(), sqlite3_aggregate_count(), ...) -- nothing on
 * this port needs the old names, and skipping them keeps the surface
 * a new app here has to pick correctly from a little smaller. */
#define SQLITE_OMIT_DEPRECATED 1

#endif
