#!/bin/bash
set -e

# Generates build/cacert_data.c: build/cacert.pem (see
# scripts/get-cacert.sh) as a C byte array, NUL-terminated --
# mbedtls_x509_crt_parse()'s own documented requirement for PEM input,
# see port/tls_shim.c's comment on why. This is the in-binary fallback
# tls_shim.c/curltest.c/wiki_discord.c fall back to when disk.img's own
# /etc/ssl/cacert.pem (port/mbedtls_port/install-cacert.sh) isn't
# available -- e.g. no disk attached at all.
#
# od+awk rather than xxd -i: both are plain coreutils, already present
# on anything this port's setup.sh already runs on, unlike xxd (a
# separate package on a minimal install) -- no new entry needed in
# setup.sh's own pre-flight command check.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APPPORT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
BUILD_DIR="$APPPORT_DIR/build"
SRC="$BUILD_DIR/cacert.pem"
OUT="$BUILD_DIR/cacert_data.c"

if [ ! -f "$SRC" ]; then
	echo "error: $SRC not found -- run scripts/get-cacert.sh first" >&2
	exit 1
fi

{
	echo "// Auto-generated by port/mbedtls_port/gen-cacert-data.sh from"
	echo "// build/cacert.pem -- do not edit by hand. See port/tls_shim.c's"
	echo "// file header for how this is used."
	echo
	echo "const unsigned char cacert_pem[] = {"
	od -An -v -tx1 "$SRC" | awk '{for (i = 1; i <= NF; i++) printf "0x%s,", $i; print ""}'
	echo "0x00"
	echo "};"
	echo
	echo "const unsigned int cacert_pem_len = sizeof(cacert_pem);"
} > "$OUT"

echo "Generated $OUT ($(wc -c < "$SRC") bytes + NUL terminator)"
